# Generated by Django 3.0.7 on 2020-09-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(default='', max_length=100)),
                ('answer1', models.CharField(default='', max_length=100, null=True)),
                ('answer2', models.CharField(default='', max_length=100, null=True)),
                ('answer3', models.CharField(default='', max_length=100, null=True)),
                ('answer4', models.CharField(default='', max_length=100, null=True)),
                ('answer5', models.CharField(default='', max_length=100, null=True)),
                ('answer6', models.CharField(default='', max_length=100, null=True)),
                ('answer7', models.CharField(default='', max_length=100, null=True)),
                ('answer8', models.CharField(default='', max_length=100, null=True)),
                ('answer9', models.CharField(default='', max_length=100, null=True)),
                ('answer10', models.CharField(default='', max_length=100, null=True)),
                ('answer11', models.CharField(default='', max_length=100, null=True)),
                ('answer12', models.CharField(default='', max_length=100, null=True)),
                ('answer13', models.TextField(default='', max_length=100, null=True)),
                ('answer14', models.TextField(default='', max_length=100, null=True)),
                ('answer15', models.TextField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('slot', models.IntegerField(default=0)),
                ('ques', models.CharField(max_length=50)),
                ('option1', models.CharField(blank=True, max_length=100, null=True)),
                ('option2', models.CharField(blank=True, max_length=100, null=True)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('ques_type', models.CharField(choices=[('Text', 'Text'), ('MCQ', 'MCQ')], max_length=5)),
                ('correct_ans', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
