# Generated by Django 3.0.6 on 2020-09-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
