# Generated by Django 3.0.7 on 2020-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
